config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'users#index'

  resources :users
  get 'oauth_redirect' => 'users#oauth_redirect'
  get 'oauth' => 'users#oauth'
  post 'oauth' => 'users#oauth'

  get 'user_timeline' => 'users#user_timeline'
  get 'posts/:id' => 'users#posts'
  get 'emotion/:id' => 'users#emotion', as: :emotion

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /oauth_redirect
  def oauth_redirect
    if params.key?('code')
      # code换取token
      response = Net::HTTP.post_form(
          URI('https://api.weibo.com/oauth2/access_token'),
          client_id:      APP_ID,
          client_secret:  APP_SECRET,
          grant_type:     'authorization_code',
          redirect_uri:   "http://#{APP_HOST}/oauth_redirect",
          code:           params['code'])
      json = JSON.parse(response.body)
      @token = json['access_token']

      # token换uid

      uri = URI.parse("https://api.weibo.com/2/account/get_uid.json?access_token=#{@token}")
      response = Net::HTTP.get_response(uri)
      json = JSON.parse(response.body)
      @uid = json['uid']
      if @uid && @token
        #user = User.find(params['user_id'])
        user = current_user
        user.weibo_uid = @uid
        user.token = @token
        user.save
        #sign_in user
      end

      redirect_to users_path
    end
  end

  def user_timeline
    uri ='https://api.weibo.com/2/statuses/user_timeline.json?'+
        "source=#{APP_ID}&access_token=#{params['access_token']}"
    response = Net::HTTP.get_response(URI(uri))
    json = JSON.parse(response.body)
    happy, unhappy, count = 0.0, 0.0, 0
    if json.key?('statuses')
      statuses = json['statuses']
      statuses.each do |s|
        text = s['text']
        current_words = ((text.scan /\[[^\[\]]+\]/).map { |x| x[1...-1] })
        h, u = get_em(current_words)
        happy += h * current_words.size
        unhappy += u * current_words.size
        s['count'] = current_words.size
        s['happy'] = h
        s['unhappy'] = u
        count += s['count']
      end
      render json: { posts: statuses, happy: happy / count, unhappy: unhappy / count }
    else
      render json: { posts: [], happy: 0, unhappy: 0 }
    end
  end

  def posts
    uri ='https://api.weibo.com/2/statuses/user_timeline.json?'+
        "source=#{APP_ID}&access_token=#{current_user.token}"
    response = Net::HTTP.get_response(URI(uri))
    json = JSON.parse(response.body)
    if json.key?('statuses')
      statuses = json['statuses']
      render json: { posts: statuses }
    else
      render json: { posts: [] }
    end
  end

  def emotion
    respond_to do |format|
      format.html do
        @user = current_user
        @token = current_user.token
      end
      format.json do
        uri ='https://api.weibo.com/2/statuses/user_timeline.json?'+
            "source=#{APP_ID}&access_token=#{current_user.token}"
        response = Net::HTTP.get_response(URI(uri))
        json = JSON.parse(response.body)
        happy, unhappy, count = 0.0, 0.0, 0
        if json.key?('statuses')
          statuses = json['statuses']
          statuses.each do |s|
            text = s['text']
            current_words = ((text.scan /\[[^\[\]]+\]/).map { |x| x[1...-1] })
            h, u = get_em(current_words)
            happy += h * current_words.size
            unhappy += u * current_words.size
            s['count'] = current_words.size
            s['happy'] = h
            s['unhappy'] = u
            count += s['count']
          end
          render json: { posts: statuses, happy: happy / count, unhappy: unhappy / count }
        else
          render json: { posts: [], happy: 0, unhappy: 0 }
        end
      end
    end

  end

  private
    def get_em(words)
      return [0.5, 0.5] unless words && words.size > 0
      uri = URI('http://api.bosondata.net/sentiment/analysis')
      res = Net::HTTP.start(uri.host, uri.port) do |http|
        req = Net::HTTP::Post.new(uri)
        req['Content-Type'] = 'application/json'
        req['X-Token'] = 'j7qM_fTv.5457.u0OqgFcklbUv'
        # The body needs to be a JSON string, use whatever you know to parse Hash to JSON
        req.body = words.to_json
        http.request(req)
      end
      result = JSON.parse(res.body)
      ret = result.reduce([0, 0]) do |sum, x|
        [sum.first + x.first, sum.last + x.last]
      end
      [ret.first / result.count, ret.last / result.count]
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoaWeibo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/emotion.html.erb
<script>
  <% if @token %>
    var token = "<%= @token %>";
    function formatPercent(val) {
      return (Math.round(val * 10000) / 100.0).toString() + " %";
    }

    $(document).ready(function() {
      if(token) {
        $.get("/user_timeline?access_token="+token, function(data, err) {
          $("#emotionInfo").text(JSON.stringify(data));
          var posts = data["posts"];
          var happy = data["happy"];
          var unhappy = data["unhappy"];
          var table = $("#emotionTable");
          table.append("<tr><th>Date</th><th>Happy</th><th>Unhappy</th></tr>");
          for(var i = 0; i < posts.length; ++i) {
            var date = new Date(Date.parse(posts[i]['created_at']));
            date = date.getUTCFullYear() + "-" + (date.getUTCMonth()+1) + "-" + date.getUTCDay().toString();
            var h = formatPercent(posts[i]['happy']);
            var u = formatPercent(posts[i]['unhappy']);
            table.append("<tr><td>"+date+"</td><td>"+h+"</td><td>"+u+"</td></tr>");
          }
          table.append("<tr><td>Total</td><td>"+formatPercent(happy)+"</td><td>"+formatPercent(unhappy)+"</td></tr>");
        });
      }
    });
  <% end %>
</script>
<table id="emotionTable"></table>
<br/><br/><br/><br/>
<div id="emotionInfo"></div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current User: <%= current_user.id %></h1>
<h2>需要先注册并且登陆才能使用瞄~😉</h2>
<% if current_user && current_user.token %>
    <%= link_to 'Test Emotion', emotion_path(current_user.id), method: :get %>
    <br/>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to 'Sina Weibo',
                'https://api.weibo.com/oauth2/authorize?' +
                    URI.encode_www_form(client_id: APP_ID,
                                        response_type: 'code',
                                        redirect_uri: "http://#{APP_HOST}/oauth_redirect"),
                method: :get %>

<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>